#!/bin/sh
CURRENT="/var/cache/eix/portage.eix"
PREVIOUS="/var/cache/eix/previous.eix"

source /lib/gentoo/functions.sh

#if [[ -e $CURRENT ]]; then
#    cp -a $CURRENT $PREVIOUS
#fi

#eix-update

if [[ -e $PREVIOUS ]]; then
    ebegin "eix-diff"
    eix-diff $PREVIOUS $CURRENT
fi
