#!/bin/bash

repository_name="${1}"
repository_path="${3}"

[[ ${repository_name} == "gentoo" ]] || exit 0

. /lib/gentoo/functions.sh

DTDDIR="${repository_path}"/metadata/news
ebegin "Updating News"
if [[ -e ${DTDDIR} ]]; then
    git -C "${DTDDIR}" pull -q --ff-only
else
    git clone -q https://anongit.gentoo.org/git/data/gentoo-news.git "${DTDDIR}"
fi
eend "$?"
